### PR TITLE
Per-file exceptions support

### LINKED ISSUE #34: Per file ignores?
Is there a way of specifying linting exceptions on a per-file basis, like with flake8?

e.g.

```
per-file-ignores =
  project/tests/*.py: S101, S105, S404, S603, S607
```

### PR DESCRIPTION
**Pull request by orsinium**
Close #34

### CODE REVIEW

**Comment by orsinium** [comment]
WIP: docs

**Comment by webknjaz** [comment]
Any chance to release it as is?

**Comment by vryazanov** [comment]
+1 for releasing it as is. really looking forward to this feature.

**Comment by orsinium** [comment]
Released in 0.4.0 :tada:

**Pull request merged**
