### PR TITLE
Allow flakehell to be installed from the source alone

### PR DESCRIPTION
**Pull request by thejcannon**
See https://flit.readthedocs.io/en/latest/pyproject_toml.html#build-system-section

This will allow `flakehell` installable from just the source. E.g. `pip install git+git+https://github.com/life4/flakehell`

### CODE REVIEW

**Comment by thejcannon** [comment]
I can't say I understand the ecosystem of `dephell` and `flit` enough to diagnose the CI failures.
The relevant info seems to be:
```bash
$ dephell deps install --env=$ENV
INFO get dependencies (format=flit, path=pyproject.toml)
INFO build dependencies graph... 
ERROR RecursionError: maximum recursion depth exceeded while getting the str of an object 
```

This seems to me like a `dephell` issue.

**Comment by mjpieters** [comment]
The build failures on Travis are not due to this pull request; a [simple change to a config file](https://travis-ci.org/github/life4/flakehell/jobs/705823771) also fails.

**Comment by mjpieters** [comment]
I can reproduce this locally, and its indeed a dephell issue, which hits an infinite recursion case when trying to test against isort. This wasn't an issue before, but isort released 5.0.0, 5.0.1, 5.0.2, 5.0.3 and 5.0.4 in the past few days. I'm seeing what needs to be done here to avoid this mess.

**Comment by mjpieters** [comment]
See https://github.com/life4/flakehell/pull/90; the trick is to pin `isort`.

**Comment by thejcannon** [comment]
@mjpieters Thanks for the diagnosis and solution! I'm subscribed to that PR and will pull the latest changes when it gets in 👍

**Comment by orsinium** [comment]
Great! Thank you all :)

**Pull request merged**
